import { Plus_Jakarta_Sans } from "next/font/google";
const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });
import "@styles/main.scss";

export const metadata = {
  title: "IEEE CSKS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
